DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE CLIENTES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nombre VARCHAR(250) NOT NULL,
  apellido VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  create_at DATE
);